name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        run: npm run lint
