name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: npm test
